port: "8001"

msql:
    username: "root"
    host: "localhost"
    port: "5432"
    dbname: "quizdb"
    sslmode: "disable"

pdb:
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "quizbd"
    sslmode: "disable"